site_name: Bosco Documentation
repo_url: https://github.com/osg-bosco/docs
copyright: Open Science Grid

theme: readthedocs

pages:
  - 'Introduction': 'index.md'
  - 'Bosco Installation': 'BoscoInstall.md'
  - 'Bosco MultiUser Installation': 'BoscoMultiUser.md'

extra_css: 
  - css/extra.css

markdown_extensions:
  - admonition
  - osg_markdown.colors
